#!/bin/sh

export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

WARNING_LEVEL=20
BATTERY_DISCHARGING=`acpi -b | grep -c "Discharging"`
BATTERY_LEVEL=`acpi -b | grep -P -o '[0-9]+(?=%)'`

EMPTU_FILE=/tmp/batteryempty
FULL_FILE=/tmp/batteryfull

if [ $BATTERY_DISCHARGING -eq 1 ] && [ -f $FULL_FILE ]; then
  rm $FULL_FILE
elif [ $BATTERY_DISCHARGING -eq 0 ] && [ -f $EMPTU_FILE ]; then
  rm $EMPTU_FILE
fi

if [ $BATTERY_LEVEL -gt 95 ] && [ $BATTERY_DISCHARGING -eq 0 ] && [ ! -f $FULL_FILE ]; then
  notify-send "Battery" "电池已充满。" -i "battery" -u low -r 3321
  touch $FULL_FILE
elif [ $BATTERY_LEVEL -le $WARNING_LEVEL ] && [ $BATTERY_DISCHARGING -eq 1 ] && [ ! -f $EMPTU_FILE ]; then
  notify-send "Low Battery" "剩余电量${BATTERY_LEVEL}%" -u critical -i "battery-alert" -r 3321
  touch $EMPTU_FILE
fi
